[workspace]
members = ["packages/*", "contracts/*"]

# Resolver has to be set explicitely in workspaces, see https://github.com/rust-lang/cargo/issues/9956
resolver = "2"

[workspace.package]
version = "3.0.0"

[workspace.dependencies]
cosmwasm-schema = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "mvp" }
cosmwasm-std = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "mvp" }
cw2 = { git = "https://github.com/permissionlessweb/cw-minus", branch = "main" }
cw-controllers = { git = "https://github.com/permissionlessweb/cw-minus", branch = "main" }
cw-multi-test = { git = "https://github.com/permissionlessweb/cw-multi-test", branch = "mvp" }
cw-storage-plus = { git = "https://github.com/permissionlessweb/cw-storage-plus", branch = "mvp" }
cw-utils = { git = "https://github.com/permissionlessweb/cw-minus", branch = "main" }
schemars             = { version = "0.8.4" }
semver               = { version = "1" }
serde                = { version = "1.0.188", default-features = false, features = ["derive"] }
thiserror            = { version = "1.0.57" }

# Packages
cw1 = { git = "https://github.com/permissionlessweb/cw-plus", branch = "main" }
cw20 = { git = "https://github.com/permissionlessweb/cw-plus", branch = "main" }
cw3 = { git = "https://github.com/permissionlessweb/cw-plus", branch = "main" }
cw4 = { git = "https://github.com/permissionlessweb/cw-plus", branch = "main" }
easy-addr            = { path = "packages/easy-addr" }

# Contracts
cw1-whitelist = { git = "https://github.com/permissionlessweb/cw-plus", branch = "main" }
cw20-base = { git = "https://github.com/permissionlessweb/cw-plus", branch = "main" }
cw3-fixed-multisig   = { path = "contracts/cw3-fixed-multisig", version = "3.0.0", features = ["library"] }
cw4-group = { git = "https://github.com/permissionlessweb/cw-plus", branch = "main" }

[profile.release.package.cw1-subkeys]
codegen-units = 1
incremental = false

[profile.release.package.cw1-whitelist]
codegen-units = 1
incremental = false

[profile.release.package.cw3-fixed-multisig]
codegen-units = 1
incremental = false

[profile.release.package.cw3-flex-multisig]
codegen-units = 1
incremental = false

[profile.release.package.cw4-group]
codegen-units = 1
incremental = false

[profile.release.package.cw4-stake]
codegen-units = 1
incremental = false

[profile.release.package.cw20-base]
codegen-units = 1
incremental = false

[profile.release.package.cw20-ics20]
codegen-units = 1
incremental = false

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false
