[workspace]
members = ["contracts/*", "packages/*"]

# Resolver has to be set explicitely in workspaces, see https://github.com/rust-lang/cargo/issues/9956
resolver = "2"

[workspace.package]
version = "3.0.0"

[workspace.dependencies]
cosmwasm-schema = { path = "../cosmwasm/packages/schema" }
cosmwasm-std = { path = "../cosmwasm/packages/std", features = ["cosmwasm_2_2"] }
cw-controllers = { path = "../cw-minus/packages/controllers" }
cw-multi-test = { package = "abstract-cw-multi-test", path = "../cw-multi-test-fork" }
cw-storage-plus = { path = "../cw-storage-plus" }
cw-utils = { path = "../cw-minus/packages/cw-utils" }
cw2 = { path = "../cw-minus/packages/cw2" }
schemars             = { version = "0.8.4" }
semver               = { version = "1" }
serde                = { version = "1.0.188", default-features = false, features = ["derive"] }
thiserror            = { version = "1.0.57" }

# Packages
cw1 = { path = "packages/cw1" }
cw20 = { path = "packages/cw20" }
cw3 = { path = "packages/cw3" }
cw4 = { path = "packages/cw4" }
easy-addr            = { path = "packages/easy-addr" }

# Contracts
cw1-whitelist = { path = "contracts/cw1-whitelist" }
cw20-base = { path = "contracts/cw20-base" }
cw3-fixed-multisig = { path = "contracts/cw3-fixed-multisig" }
cw4-group = { path = "contracts/cw4-group" }

[patch.'https://github.com/permissionlessweb/cw-plus']
cw1 = { path = "packages/cw1" }
cw1-subkeys = { path = "contracts/cw1-subkeys" }
cw1-whitelist = { path = "contracts/cw1-whitelist" }
cw20 = { path = "packages/cw20" }
cw20-base = { path = "contracts/cw20-base" }
cw20-ics20 = { path = "contracts/cw20-ics20" }
cw3 = { path = "packages/cw3" }
cw3-fixed-multisig = { path = "contracts/cw3-fixed-multisig" }
cw3-flex-multisig = { path = "contracts/cw3-flex-multisig" }
cw4 = { path = "packages/cw4" }
cw4-group = { path = "contracts/cw4-group" }
cw4-stake = { path = "contracts/cw4-stake" }

[profile.release]
rpath = false
lto = true
overflow-checks = true
opt-level = 3
debug = false
debug-assertions = false

[profile.release.package.cw1-subkeys]
codegen-units = 1
incremental = false

[profile.release.package.cw1-whitelist]
codegen-units = 1
incremental = false

[profile.release.package.cw3-fixed-multisig]
codegen-units = 1
incremental = false

[profile.release.package.cw3-flex-multisig]
codegen-units = 1
incremental = false

[profile.release.package.cw4-group]
codegen-units = 1
incremental = false

[profile.release.package.cw4-stake]
codegen-units = 1
incremental = false

[profile.release.package.cw20-base]
codegen-units = 1
incremental = false

[profile.release.package.cw20-ics20]
codegen-units = 1
incremental = false
